import { DevtoolsProvider } from "@providers/devtools";
import { useNotificationProvider } from "@refinedev/antd";
import { GitHubBanner, Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AppIcon } from "@components/app-icon";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProviderClient } from "@providers/auth-provider/auth-provider.client";
import { dataProvider } from "@providers/data-provider";
import "@refinedev/antd/dist/reset.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      {/* <head>
        <Script
          strategy="beforeInteractive"
          src="https://raw.githack.com/AR-js-org/studio-backend/master/src/modules/marker/tools/gesture-detector.js"
        />
        <Script
          strategy="beforeInteractive"
          src="https://raw.githack.com/AR-js-org/studio-backend/master/src/modules/marker/tools/gesture-handler.js"
        />
        <Script
          strategy="beforeInteractive"
          src="https://aframe.io/releases/0.9.2/aframe.min.js"
        />
        <Script
          strategy="beforeInteractive"
          src="https://raw.githack.com/jeromeetienne/AR.js/master/aframe/build/aframe-ar.min.js"
        />
        <Script
          strategy="beforeInteractive"
          src="https://raw.githack.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"
        />
      </head> */}
      <body>
        <Suspense>
          <RefineKbarProvider>
            <AntdRegistry>
              <ColorModeContextProvider defaultMode={defaultMode}>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    authProvider={authProviderClient}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    resources={[
                      {
                        name: "email",
                        list: "/email",
                        meta: {
                          label: "Email",
                        },
                      },
                      {
                        name: "dashboard",
                        list: "/dashboard",
                        meta: {
                          label: "Dashboard",
                        },
                      },
                      {
                        name: "chat",
                        list: "/chat",
                        meta: {
                          label: "Chat",
                        },
                      },
                      {
                        name: "orders",
                        list: "/orders",
                        create: "/orders/create",
                        edit: "/orders/edit/:id",
                        show: "/orders/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "products",
                        list: "/products",
                        create: "/products/create",
                        edit: "/products/edit/:id",
                        show: "/products/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "reviews",
                        list: "/reviews",
                        create: "/reviews/create",
                        edit: "/reviews/edit/:id",
                        show: "/reviews/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "categories",
                        list: "/categories",
                        create: "/categories/create",
                        edit: "/categories/edit/:id",
                        show: "/categories/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "ARCollectible",
                        list: "/ARCollectible",
                        create: "/ARCollectible/create",
                        edit: "/ARCollectible/edit/:id",
                        show: "/ARCollectible/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "5cmi4w-Ed9MXc-08CvC5",
                      title: { text: "Hope World", icon: <AppIcon /> },
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </ColorModeContextProvider>
            </AntdRegistry>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
