import { DevtoolsProvider } from "@providers/devtools";
import { useNotificationProvider } from "@refinedev/antd";
import { GitHubBanner, Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AppIcon } from "@components/app-icon";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { dataProvider } from "data-provider-package";
import { authProviderClient } from "auth-provider-client";
import liveProvider from "live-provider";

import "@refinedev/antd/dist/reset.css";
import Script from "next/script";
import {
  DashboardOutlined,
  EyeOutlined,
  MailOutlined,
  MessageOutlined,
  OrderedListOutlined,
  ProductOutlined,
  ReadOutlined,
  TeamOutlined,
} from "@ant-design/icons";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <AntdRegistry>
              <ColorModeContextProvider defaultMode={defaultMode}>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    authProvider={authProviderClient}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    liveProvider={liveProvider}
                    resources={[
                      {
                        name: "email",
                        list: "/email",
                        meta: {
                          label: "Email",
                          icon: <MailOutlined />,
                        },
                      },
                      {
                        name: "dashboard",
                        list: "/dashboard",
                        meta: {
                          label: "Dashboard",
                          icon: <DashboardOutlined />,
                        },
                      },
                      {
                        name: "chat",
                        list: "/chat",
                        meta: {
                          label: "Chat",
                          icon: <MessageOutlined />,
                        },
                      },
                      {
                        name: "orders",
                        list: "/orders",
                        create: "/orders/create",
                        edit: "/orders/edit/:id",
                        show: "/orders/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "products",
                        list: "/products",
                        create: "/products/create",
                        edit: "/products/edit/:id",
                        show: "/products/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <ProductOutlined />,
                        },
                      },
                      {
                        name: "reviews",
                        list: "/reviews",
                        create: "/reviews/create",
                        edit: "/reviews/edit/:id",
                        show: "/reviews/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <ReadOutlined />,
                        },
                      },
                      {
                        name: "categories",
                        list: "/categories",
                        create: "/categories/create",
                        edit: "/categories/edit/:id",
                        show: "/categories/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <OrderedListOutlined />,
                        },
                      },
                      // {
                      //   name: "subcategories",
                      //   list: "/subcategories",
                      //   create: "/subcategories/create",
                      //   edit: "/subcategories/edit/:id",
                      //   show: "/subcategories/show/:id",
                      //   meta: {
                      //     canDelete: true,
                      //     icon: <OrderedListOutlined />,
                      //   },
                      // },
                      {
                        name: "ARCollectible",
                        list: "/ARCollectible",
                        create: "/ARCollectible/create",
                        edit: "/ARCollectible/edit/:id",
                        show: "/ARCollectible/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <EyeOutlined />,
                        },
                      },
                      {
                        name: "users",
                        list: "/users",
                        create: "/users/create",
                        edit: "/users/edit/:id",
                        show: "/users/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <OrderedListOutlined />,
                        },
                      },
                      {
                        name: "profiles",
                        list: "/profiles",
                        create: "/profiles/create",
                        edit: "/profiles/edit/:id",
                        show: "/profiles/show/:id",
                        meta: {
                          canDelete: true,
                          hide: true,
                          icon: <TeamOutlined />,
                        },
                      },
                      // {
                      //   name: "profiles_with_roles",
                      //   list: "/profiles_with_roles",
                      //   meta: {
                      //     label: "User Roles",
                      //     icon: <TeamOutlined />,
                      //     hide: true,
                      //     dataProviderName: "default",
                      //   },
                      // },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "5cmi4w-Ed9MXc-08CvC5",
                      title: { text: "Hope World", icon: <AppIcon /> },
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </ColorModeContextProvider>
            </AntdRegistry>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
