alter type "public"."app_permission" rename to "app_permission__old_version_to_be_dropped";

create type "public"."app_permission" as enum ('products.delete', 'orders.delete', 'products.create', 'products.read', 'products.update', 'AR.create', 'AR.read', 'AR.update', 'AR.delete');

-- First convert the column to text to break the dependency
alter table "public"."role_permissions" alter column "permission" set data type text using "permission"::text;

-- Let's add a check for other dependencies
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (
        SELECT 
            pg_describe_object(d.classid, d.objid, d.objsubid) as dependent_object,
            n.nspname as schema_name,
            c.relname as relation_name,
            a.attname as column_name
        FROM pg_depend d
        JOIN pg_class c ON c.oid = d.objid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        LEFT JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = d.objsubid
        WHERE d.refclassid = 'pg_type'::regclass 
        AND d.refobjid = 'public.app_permission__old_version_to_be_dropped'::regtype
    ) LOOP
        RAISE NOTICE 'Found dependency: %', r.dependent_object;
        IF r.column_name IS NOT NULL THEN
            EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN %I TYPE text USING %I::text',
                        r.schema_name, r.relation_name, r.column_name, r.column_name);
        END IF;
    END LOOP;
END $$;

-- Comment out the drop for now
-- drop type "public"."app_permission__old_version_to_be_dropped";

create table "public"."ARCollectible" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "image" text
);

-- Rest of the file remains unchanged, but comment out the second drop statement as well
alter table "public"."ARCollectible" enable row level security;

create table "public"."orders" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."orders" enable row level security;

create table "public"."reviews" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "rating" integer,
    "comment" text,
    "product_id" bigint
);


alter table "public"."reviews" enable row level security;

-- Keep only this drop statement, but add CASCADE
drop type "public"."app_permission__old_version_to_be_dropped" CASCADE;

alter table "public"."products" add column "category" text;

alter table "public"."products" add column "images" text;

alter table "public"."products" add column "review_id" bigint;

-- Remove this duplicate line that's causing the error
-- alter table "public"."role_permissions" alter column "permission" set data type text using "permission"::text;

alter table "public"."user_roles" alter column "role" drop not null;

CREATE UNIQUE INDEX "ARCollectible_pkey" ON public."ARCollectible" USING btree (id);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (id);

alter table "public"."ARCollectible" add constraint "ARCollectible_pkey" PRIMARY KEY using index "ARCollectible_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."reviews" add constraint "reviews_pkey" PRIMARY KEY using index "reviews_pkey";

alter table "public"."products" add constraint "products_review_id_fkey" FOREIGN KEY (review_id) REFERENCES reviews(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."products" validate constraint "products_review_id_fkey";

alter table "public"."reviews" add constraint "reviews_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_product_id_fkey";

set check_function_bodies = off;

-- Add the authorize function
CREATE OR REPLACE FUNCTION public.authorize(permission app_permission)
RETURNS boolean
LANGUAGE plpgsql
AS $function$
BEGIN
    -- Check if the current user has the required permission
    RETURN EXISTS (
        SELECT 1
        FROM public.role_permissions rp
        JOIN public.user_roles ur ON ur.role = rp.role
        WHERE ur.user_id = auth.uid()
        AND rp.permission = authorize.permission
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$declare
    claims jsonb;
    user_role public.app_role;
  begin
    -- Fetch the user role in the user_roles table using LEFT JOIN
    select ur.role into user_role
    from public.user_roles ur
    where ur.user_id = (event->>'user_id')::uuid;

    claims := event->'claims';

    if user_role is not null then
        -- Set the claim
        claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
    else
        claims := jsonb_set(claims, '{user_role}', '"customer"');
    end if;

    -- Update the 'claims' object in the original event
    event := jsonb_set(event, '{claims}', claims);

    -- Return the modified or original event
    return event;
  end;$function$
;

grant delete on table "public"."ARCollectible" to "anon";

grant insert on table "public"."ARCollectible" to "anon";

grant references on table "public"."ARCollectible" to "anon";

grant select on table "public"."ARCollectible" to "anon";

grant trigger on table "public"."ARCollectible" to "anon";

grant truncate on table "public"."ARCollectible" to "anon";

grant update on table "public"."ARCollectible" to "anon";

grant delete on table "public"."ARCollectible" to "authenticated";

grant insert on table "public"."ARCollectible" to "authenticated";

grant references on table "public"."ARCollectible" to "authenticated";

grant select on table "public"."ARCollectible" to "authenticated";

grant trigger on table "public"."ARCollectible" to "authenticated";

grant truncate on table "public"."ARCollectible" to "authenticated";

grant update on table "public"."ARCollectible" to "authenticated";

grant delete on table "public"."ARCollectible" to "service_role";

grant insert on table "public"."ARCollectible" to "service_role";

grant references on table "public"."ARCollectible" to "service_role";

grant select on table "public"."ARCollectible" to "service_role";

grant trigger on table "public"."ARCollectible" to "service_role";

grant truncate on table "public"."ARCollectible" to "service_role";

grant update on table "public"."ARCollectible" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."reviews" to "anon";

grant insert on table "public"."reviews" to "anon";

grant references on table "public"."reviews" to "anon";

grant select on table "public"."reviews" to "anon";

grant trigger on table "public"."reviews" to "anon";

grant truncate on table "public"."reviews" to "anon";

grant update on table "public"."reviews" to "anon";

grant delete on table "public"."reviews" to "authenticated";

grant insert on table "public"."reviews" to "authenticated";

grant references on table "public"."reviews" to "authenticated";

grant select on table "public"."reviews" to "authenticated";

grant trigger on table "public"."reviews" to "authenticated";

grant truncate on table "public"."reviews" to "authenticated";

grant update on table "public"."reviews" to "authenticated";

grant delete on table "public"."reviews" to "service_role";

grant insert on table "public"."reviews" to "service_role";

grant references on table "public"."reviews" to "service_role";

grant select on table "public"."reviews" to "service_role";

grant trigger on table "public"."reviews" to "service_role";

grant truncate on table "public"."reviews" to "service_role";

grant update on table "public"."reviews" to "service_role";

create policy "Add authorized delete"
on "public"."ARCollectible"
as permissive
for delete
to authenticated
using (authorize('AR.delete'::app_permission));


create policy "Add authorized update"
on "public"."ARCollectible"
as permissive
for update
to authenticated
using (authorize('AR.update'::app_permission));


create policy "Allow authorized create"
on "public"."ARCollectible"
as permissive
for insert
to authenticated
with check (authorize('AR.create'::app_permission));


create policy "Enable read access for authenticated users"
on "public"."ARCollectible"
as permissive
for select
to authenticated
using (true);



